In [ ]:
from tensorflow.keras.datasets import mnist
import tensorflow as tf
import matplotlib.pyplot as plt 
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.image import load_img, img_to_array, smart_resize
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
p = Path().cwd()
print(p)
q = p/'drive'/'MyDrive'/'Colab Notebooks'/'waste1' # use p to create a path to the data 
print(q)
target_dict = dict([("Dump", 0),("Inter",1),("Loaded",2),("Unloaded",3)]) # create dictionary mapping Lego block type to integer label 
images = [] # create an empty list
labels = [] # create an empty list

/content
/content/drive/MyDrive/Colab Notebooks/waste1


In [ ]:
for fldr in q.iterdir(): 
  print(fldr.name)
  current_label = fldr.name
  for img in fldr.iterdir():
    img = load_img(img)
    img_array = img_to_array(img)
    size = (180,320)
    img_array_resized = smart_resize(img_array,size)
    images.append(img_array_resized)
    labels.append(current_label)

images = np.array(images) 
labels = np.array(labels)

Dump
Unloaded
Inter
Loaded


In [ ]:
labels_int = [] # use the target_dict to convert the string labels to an array of integers
print(target_dict)
for i in labels:
      n_key = target_dict[i]
      labels_int.append(n_key)
print(labels_int)
labels_int = np.array(labels_int)

{'Dump': 0, 'Inter': 1, 'Loaded': 2, 'Unloaded': 3}
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(images, labels_int, test_size=0.2, random_state=1)


In [ ]:
X_train.shape

(642, 180, 320, 3)

In [ ]:
X_test.shape

(161, 180, 320, 3)

In [ ]:
y_train.shape

(642,)

In [ ]:
y_test.shape

(161,)

In [ ]:
X_train =X_train.reshape(642,172800)
X_test =X_test.reshape(161,172800)



In [ ]:
## HyperBuild Random Forest Model with hyperparameters

In [ ]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 80, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [2,4]
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
# Method of selecting samples for training each tree
bootstrap = [True, False]

In [ ]:
# Create the param grid
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(param_grid)

{'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72, 80], 'max_features': ['auto', 'sqrt'], 'max_depth': [2, 4], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False]}


In [ ]:
rf_Model = RandomForestClassifier()

In [ ]:
from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = rf_Model, param_grid = param_grid, cv = 3, verbose=2, n_jobs = 4)

In [ ]:
rf_Grid.fit(X_train, y_train)


Fitting 3 folds for each of 320 candidates, totalling 960 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=4,
             param_grid={'bootstrap': [True, False], 'max_depth': [2, 4],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [10, 17, 25, 33, 41, 48, 56, 64, 72,
                                          80]},
             verbose=2)

In [ ]:
rf_Grid.best_params_

{'bootstrap': True,
 'max_depth': 4,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 56}

In [ ]:
print (f'Train Accuracy - : {rf_Grid.score(X_train,y_train):.3f}')
print (f'Test Accuracy - : {rf_Grid.score(X_test,y_test):.3f}')

Train Accuracy - : 0.941
Test Accuracy - : 0.938


In [ ]:
from math import sqrt
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=56,bootstrap=True,max_depth=4,max_features='auto',min_samples_leaf=1,min_samples_split=5 )

model.fit(X_train,y_train)


RandomForestClassifier(max_depth=4, min_samples_split=5, n_estimators=56)

In [ ]:
image_pred = model.predict(X_test)
image_pred

array([0, 2, 1, 3, 1, 3, 0, 2, 2, 2, 1, 0, 3, 2, 0, 3, 1, 2, 1, 3, 1, 3,
       1, 0, 3, 3, 2, 0, 2, 0, 2, 0, 0, 0, 1, 0, 1, 3, 3, 1, 1, 3, 0, 2,
       1, 0, 3, 1, 3, 2, 2, 0, 1, 2, 0, 2, 3, 1, 3, 1, 3, 3, 1, 0, 1, 3,
       0, 2, 1, 2, 1, 2, 3, 1, 0, 3, 2, 1, 2, 0, 0, 0, 3, 0, 3, 0, 1, 0,
       3, 0, 0, 0, 1, 0, 3, 3, 1, 3, 3, 0, 2, 0, 2, 2, 3, 3, 0, 1, 1, 2,
       2, 0, 1, 3, 0, 2, 3, 2, 0, 0, 2, 0, 2, 1, 0, 1, 1, 0, 2, 1, 2, 2,
       0, 3, 1, 3, 0, 0, 0, 3, 0, 1, 0, 2, 0, 2, 3, 3, 3, 1, 1, 2, 1, 1,
       0, 1, 0, 3, 2, 0, 2])

In [ ]:
trainpred = model.predict(X_train)
trainpred

array([3, 1, 2, 0, 2, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 3, 0, 2, 0, 0, 1, 0,
       2, 0, 1, 3, 3, 2, 0, 1, 3, 2, 1, 0, 0, 0, 2, 2, 3, 3, 2, 2, 2, 0,
       0, 0, 3, 3, 1, 3, 2, 3, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1,
       0, 2, 3, 0, 0, 3, 3, 2, 2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0,
       0, 3, 0, 2, 3, 0, 2, 1, 0, 3, 2, 1, 0, 3, 1, 0, 2, 3, 2, 3, 0, 2,
       3, 0, 2, 3, 1, 3, 2, 0, 2, 0, 1, 1, 3, 3, 2, 1, 0, 0, 1, 0, 0, 2,
       2, 2, 0, 0, 3, 2, 1, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 3, 3, 0, 1, 1,
       2, 0, 0, 3, 3, 1, 0, 0, 2, 2, 0, 3, 3, 1, 1, 0, 2, 2, 3, 0, 0, 0,
       0, 0, 0, 3, 2, 3, 3, 1, 0, 2, 2, 3, 1, 0, 2, 3, 2, 0, 2, 3, 2, 1,
       0, 0, 1, 1, 2, 3, 2, 3, 0, 1, 3, 0, 2, 0, 0, 3, 2, 1, 0, 1, 0, 2,
       2, 2, 3, 2, 2, 2, 0, 3, 2, 1, 2, 0, 1, 2, 0, 0, 1, 3, 2, 1, 3, 2,
       2, 0, 0, 0, 1, 1, 0, 0, 2, 0, 3, 0, 3, 0, 2, 3, 0, 1, 1, 3, 1, 0,
       2, 0, 0, 3, 2, 3, 2, 1, 3, 0, 2, 3, 2, 2, 0, 2, 3, 0, 0, 2, 0, 3,
       3, 0, 2, 1, 3, 0, 0, 3, 3, 3, 0, 1, 3, 2, 2,

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


accuracy_score(image_pred,y_test)
print(classification_report(image_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.79      0.88        48
           1       0.78      0.97      0.86        39
           2       0.97      1.00      0.99        36
           3       1.00      0.97      0.99        38

    accuracy                           0.93       161
   macro avg       0.94      0.93      0.93       161
weighted avg       0.94      0.93      0.93       161



In [ ]:
accuracy_score(trainpred,y_train)
print(classification_report(trainpred,y_train))

              precision    recall  f1-score   support

           0       0.99      0.83      0.90       203
           1       0.76      0.99      0.86       120
           2       1.00      1.00      1.00       169
           3       1.00      0.98      0.99       150

    accuracy                           0.94       642
   macro avg       0.94      0.95      0.94       642
weighted avg       0.95      0.94      0.94       642



In [ ]:
p = Path().cwd()
print(p)
q = p/'drive'/'MyDrive'/'Colab Notebooks'/'test' # use p to create a path to the data 
print(q)
target_dict = dict([("Drop off", 0),("Pick up",1),("Dump",2)]) # create dictionary mapping Lego block type to integer label 
images = [] # create an empty list
labels = [] # create an empty list

/content
/content/drive/MyDrive/Colab Notebooks/test


In [ ]:
for fldr in q.iterdir(): 
  print(fldr.name)
  current_label = fldr.name
  for img in fldr.iterdir():
    img = load_img(img)
    img_array = img_to_array(img)
    size = (180,320)
    img_array_resized = smart_resize(img_array,size)
    images.append(img_array_resized)
    labels.append(current_label)

images = np.array(images) 
labels = np.array(labels)

Dump
Pick up
Drop off


In [ ]:
labels_int = [] # use the target_dict to convert the string labels to an array of integers
print(target_dict)
for i in labels:
      n_key = target_dict[i]
      labels_int.append(n_key)
print(labels_int)
labels_int = np.array(labels_int)

{'Drop off': 0, 'Pick up': 1, 'Dump': 2}
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
images.shape

(151, 180, 320, 3)

In [ ]:
labels_int.shape

(151,)

In [ ]:
images =images.reshape(151,172800)


In [ ]:
test_pred = model.predict(images)
test_pred

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 1000 out of 1000 | elapsed:    0.1s finished


array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1,
       2, 2, 1, 1, 1, 1, 3, 2, 3, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1,
       1, 1, 2, 1, 3, 2, 1, 3, 1, 1, 3, 2, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3,
       3, 3, 2, 2, 3, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 3, 1, 1, 3, 2, 2, 1,
       1, 3, 2, 2, 1, 2, 2, 3, 2, 1, 1, 1, 1, 2, 3, 2, 2, 2, 3])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


accuracy_score(test_pred,labels_int)
print(classification_report(test_pred,labels_int))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.67      0.19      0.30        42
           2       0.77      0.57      0.65        81
           3       0.00      0.00      0.00        16

    accuracy                           0.36       151
   macro avg       0.36      0.19      0.24       151
weighted avg       0.60      0.36      0.43       151



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
confusion_matrix(test_pred,labels_int)


array([[ 0,  0, 12,  0],
       [32,  8,  2,  0],
       [31,  4, 46,  0],
       [16,  0,  0,  0]])